server {
    listen 443 ssl;
    server_name demo.intellica.io;
    ssl_certificate     /etc/nginx/certs/demo.crt;
    ssl_certificate_key /etc/nginx/certs/demo.key;

    location / {
        proxy_pass http://cortex:8787;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
