#!/bin/bash
set -e
cd "$(dirname "$0")/.."
echo "=== Cortex Demo Statistics ==="
echo ""
echo "Work Orders:"
docker compose exec -T db psql -U cortex -d cortex_demo -c "SELECT status, count(*) FROM demo_work_orders GROUP BY status ORDER BY count DESC;"
echo ""
echo "Absorption Progress:"
docker compose exec -T db psql -U cortex -d cortex_demo -c "SELECT source_application, fields_discovered, fields_absorbed, absorption_phase FROM source_systems;"
echo ""
echo "Provenance Capsules:"
docker compose exec -T db psql -U cortex -d cortex_demo -c "SELECT count(*) AS total_capsules FROM demo_provenance;"
echo ""
echo "Decision Traces:"
docker compose exec -T db psql -U cortex -d cortex_demo -c "SELECT count(*) AS total_traces FROM decision_traces;"
echo ""
echo "Registered Tools:"
docker compose exec -T db psql -U cortex -d cortex_demo -c "SELECT name, description FROM tools ORDER BY name;"
